// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"time"
)

type Tasks struct {
	ID              int64     `json:"id"`
	TaskName        string    `json:"task_name"`
	TaskDescription string    `json:"task_description"`
	CreatedAt       time.Time `json:"created_at"`
	DueDate         time.Time `json:"due_date"`
	TaskStatus      string    `json:"task_status"`
}
